name: Flutter Web

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{secrets.commit_secret}} 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --release
      - run: |
          cd build/web
          git init
          git config --global user.email corronade@gmail.com
          git config --global user.name CJHJ
          git status
          git remote add origin https://${{secrets.commit_secret}}@github.com/CJHJ/cjhj.github.io.git
          git checkout master
          git add --all
          git commit -m "Update page"
          git push origin master -f